Customizable output directories for validation
Path to validation output can be customized via an environment variable
NS_VALIDATION_PATH_FORMAT which will substitute the following keys:

    %T    Timestamp of invocation of install-local.sh.
    %H    Git commit hash of nsuite (with + on end if modified).
    %h    Git commit short hash of nsuite (with + on end if modified).
    %S    System name, as defined in system environment script or else
          host name.
    %s    Simulator name.
    %m    Model name.
    %p    Parameter set name.

* Tidy up git-repo-hash and use -C option to specify repo path in git commands.
* Record installation timestamp and system name.
* Export ns_ path variables, together with ns_timestamp and ns_sysname.
* Use NS_VALIDATION_PATH_FORMAT environment variable to specify
validation output path, defaulting to %s/%m/%p (sim/model/paramset).

diff --git a/common/bin/git-repo-hash b/common/bin/git-repo-hash
--- a/common/bin/git-repo-hash
+++ b/common/bin/git-repo-hash
@@ -13,29 +13,43 @@ _end_
 }
 
 unset eoo
+unset repohome
+
 gitformat="%H"
-while [[ $# > 0 ]]; do
+while [[ $# > 0 && -z "$eoo" ]]; do
     case $1 in
-	-h | --help )
-	    usage
-	    exit 0
-	    ;;
-	-s | --short )
-	    gitformat="%h"
-	    ;;
-	-- )
-	    eoe=1
-	* )
-	    cd "$1"
+        -h | --help )
+            usage
+            exit 0
+            ;;
+        -s | --short )
+            gitformat="%h"
+            shift
+            ;;
+        -- )
+            shift
+            break
+            ;;
+        * )
+            break
     esac
-    shift
 done
 
-if git_commit=$(git log -1 --pretty=format:$gitformat 2>/dev/null); then
-    git diff --quiet HEAD 2>/dev/null || git_commit+="+"
+if [[ $# > 1 ]]; then
+    cat >&2 <<_end_
+git-repo-hash: too many arguments
+Try 'git-repo-hash --help' for more information.
+_end_
+    exit 1
+fi
+
+[[ $# > 0 ]] && repohome=(-C "$1")
+
+if git_commit=$(git "${repohome[@]}" log -1 --pretty=format:$gitformat 2>/dev/null); then
+    git "${repohome[@]}" diff --quiet HEAD 2>/dev/null || git_commit+="+"
     echo "${git_commit}"
 else
-    echo "failed to inspect git repo" >&2
+    echo "git-repo-hash: failed to inspect git repo" >&2
     exit 1
 fi
 
