Complete rc-exp2syn-spike test for Arbor, NEURON.
CoreNEURON still TODO.

* Add some very preliminary documentation for rc-exp2syn-spike test.
* Use a parameter value `max_error` to set the pass/fail threshold for
rc-exp2syn-spike, given that it should be a function of the `dt` value.
* Fix bug in `run-validation.sh` that caused it to run only some of the
models by default.

diff --git a/validation/rc-exp2syn-spike/run b/validation/rc-exp2syn-spike/run
--- a/validation/rc-exp2syn-spike/run
+++ b/validation/rc-exp2syn-spike/run
@@ -7,17 +7,17 @@ cd "${BASH_SOURCE[0]%/*}"
 
 # Set up model paths and model_XXX variables.
 source "$ns_base_path/scripts/model_common.sh"
-model_setup rc-exp2syn-spikes "$@"
+model_setup rc-exp2syn-spike "$@"
 
 # Run sim-specific model with parameter data.
 #
 # Expected output variables:
-#     v0      voltage trace of cell 0 soma (dimension time)
-#     v1      voltage trace of cell 1 soma (dimension time)
+#     v0      voltage trace of cell 0 soma (dimension t0)
+#     v1      voltage trace of cell 1 soma (dimension t1)
 #     spike0  scalar time of first spike cell 0
 #     spike1  scalar time of first spike cell 1
 #
-# For CoreNEURON, voltage traces will be omitted; pass/fail
+# For CoreNEURON, voltage traces will be omitted; the pass/fail
 # test only looks at spike time differences.
 
 outfile="$model_output_dir/run.nc"
@@ -26,12 +26,24 @@ outfile="$model_output_dir/run.nc"
 # Generate reference data if required.
 reffile=$(model_find_cacheable "ref-${model_name}-${model_param}.nc")
 if [ $? -ne 0 -o -n "$model_refresh" ]; then 
-    generate-rc-exp2syn-spikes "$reffile" $model_param_data
+    generate-rc-exp2syn-spike "$reffile" $model_param_data
 fi
 
 # Run comparison.
 deltafile="$model_output_dir/delta.nc"
-comparex "$outfile" --warn --ref "$reffile" --interpolate time -o "$deltafile"
+comparex "$outfile" --warn --ref "$reffile" --var spike0 --var spike1 -o "$deltafile"
 
-thresholdx "$deltafile" -e "voltage.relerr.lb<0.01" > "$model_status_path"
+# Get threshold from parameter data 'max_error'
+max_error=
+for param in $model_param_data; do
+    if [[ "$param" =~ ^'max_error='(.*) ]]; then
+	max_error=${BASH_REMATCH[1]}
+    fi
+done
+if [ -z "$max_error" ]; then
+    echo 'Missing max_error in parameter set' >&2
+    exit 1
+fi
+
+thresholdx "$deltafile" -e "spike0.abserr<$max_error" -e "spike1.abserr<$max_error" > "$model_status_path"
 model_notify_pass_fail $?
